### ISSUE TITLE
Error Running airflow module3-demo1 

### ISSUE THREAD

**Issue by soumilshah1995** [axel-sirota/productionalizing-data-pipelines-airflow#1]
![image](https://user-images.githubusercontent.com/39345855/105486625-c70ab580-5c7c-11eb-8bd1-b0e416932e7a.png)

**Comment by soumilshah1995** [comment]
issue in file start-airflow.sh

**Comment by axel-sirota** [comment]
Hi! Thanks for doing the course! What is your OS and bash version?

**Comment by soumilshah1995** [comment]
> Hi! Thanks for doing the course! What is your OS and bash version?

well using windows 10 OS 
using docker container for Linux :D

**Comment by axel-sirota** [comment]
which container? The ubuntu one? Can you share more logs? You don't have bash installed there?

**Comment by mjjimenez** [comment]
I had the same problem on windows 10.

Here are the logs for the error:

![module3-demo1](https://user-images.githubusercontent.com/4151269/107856854-071d1c80-6e66-11eb-8462-1bb3a0028ba1.png)

**Comment by axel-sirota** [comment]
This is weird... it is complaining bash is not existent, however that is not the host but the image that was built...  could you please give me full output?

Also, what is your docker version? Is it docker for windows? Let's try this:

Please run (I am assuming the airflow image was built correctly) [some may fail and that is key to understanding this]:

- `docker run -it pluralsight/airflow /bin/bash ` : If you enter a subshell please tell me so 

-  `docker run pluralsight/airflow /bin/sh `  : If you enter a subshell please tell me so 

- `docker run pluralsight/airflow /usr/bin/env bash `   : If you enter a subshell please tell me so 

Thanks!

**Comment by mjjimenez** [comment]
I'm having trouble with my docker daemon right now, but I have a guess that the `start-airflow.sh` file uses \r for newline so the container is looking for a `bash\r` shell. Should we replace all the \r characters in script files to be \n ?

**Comment by axel-sirota** [comment]
I found the issue! The files in git are correct, but the issue is your git daemon in windows that "auto transforms" the line endings for Windows :) 

On windows git is configured to retransform line endings into "Windows Style" (\n to \r\n), however, then docker gets lost because docker images are Unix. I recommend the following:

git clone https://github.com/axel-sirota/productionalizing-data-pipelines-airflow.git --config core.autocrlf=input

This will set the line endings correctly! :)

**Comment by soumilshah1995** [comment]
@axel-sirota   please check this https://github.com/soumilshah1995/Airflow-Tutorials-/tree/main/Tutorial4
this is what works for me
