### ISSUE TITLE
Airflow 2.0 support

### ISSUE THREAD

**Issue by dougpool** [axel-sirota/productionalizing-data-pipelines-airflow#2]
Would be nice to have Airflow 2.0 versions of the course modules.

Nice job on the pluralsight course

**Comment by axel-sirota** [comment]
That is an excellent idea! I proposed it to Pluralsight but they thought for now it was best to keep it at 1.10. However in a year in the update I will try to add something about Airflow 2.0 when it is more stable for more people!
